pytest req

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -60,54 +60,55 @@ steps:
   #     - "distro=amazonlinux"
   #   branches: "!master"
 
-  - label: "sanity checks"
-    command: |
-      source ~/.cargo/env && set -eux
-      rustc --version && cargo --version
-      cargo run -p themis --release
-      if [ -e deny.toml ]; then
-        cargo-deny --all-features check bans
-      fi
-      cargo check --workspace --all-targets --all-features
-      cargo check -p neard --features test_features
-      cargo check -p neard --features sandbox
+  # - label: "sanity checks"
+  #   command: |
+  #     source ~/.cargo/env && set -eux
+  #     rustc --version && cargo --version
+  #     cargo run -p themis --release
+  #     if [ -e deny.toml ]; then
+  #       cargo-deny --all-features check bans
+  #     fi
+  #     cargo check --workspace --all-targets --all-features
+  #     cargo check -p neard --features test_features
+  #     cargo check -p neard --features sandbox
 
-      cargo build -p neard --bin neard --features nightly
-      cd pytest
-      python3 -m pip install --progress-bar off --user -r requirements.txt
-      python3 tests/sanity/spin_up_cluster.py
-      cd ..
-      # Note: We’re not running spin_up_cluster.py for non-nightly
-      # because spinning up non-nightly clusters is already covered
-      # by other steps in the CI, e.g. upgradable.
+  #     cargo build -p neard --bin neard --features nightly
+  #     cd pytest
+  #     python3 -m pip install --progress-bar off --user -r requirements.txt
+  #     python3 tests/sanity/spin_up_cluster.py
+  #     cd ..
+  #     # Note: We’re not running spin_up_cluster.py for non-nightly
+  #     # because spinning up non-nightly clusters is already covered
+  #     # by other steps in the CI, e.g. upgradable.
 
-      cargo build -p neard --bin neard
-      python3 scripts/state/update_res.py check
+  #     cargo build -p neard --bin neard
+  #     python3 scripts/state/update_res.py check
 
-      python3 scripts/check_nightly.py
-      python3 scripts/check_pytests.py
-      python3 scripts/check_fuzzing.py
+  #     python3 scripts/check_nightly.py
+  #     python3 scripts/check_pytests.py
+  #     python3 scripts/check_fuzzing.py
 
-      ./scripts/formatting --check
+  #     ./scripts/formatting --check
 
-      ./scripts/run_clippy.sh
+  #     ./scripts/run_clippy.sh
 
-      rm target/rpc_errors_schema.json
-      cargo check -p near-jsonrpc --features dump_errors_schema
-      if ! git --no-pager diff --no-index chain/jsonrpc/res/rpc_errors_schema.json target/rpc_errors_schema.json; then
-          set +x
-          echo 'The RPC errors schema reflects outdated typing structure; please run'
-          echo '    ./chain/jsonrpc/build_errors_schema.sh'
-          exit 1
-      fi >&2
-    timeout: 30
-    agents:
-      - "distro=amazonlinux"
-    branches: "!master"
+  #     rm target/rpc_errors_schema.json
+  #     cargo check -p near-jsonrpc --features dump_errors_schema
+  #     if ! git --no-pager diff --no-index chain/jsonrpc/res/rpc_errors_schema.json target/rpc_errors_schema.json; then
+  #         set +x
+  #         echo 'The RPC errors schema reflects outdated typing structure; please run'
+  #         echo '    ./chain/jsonrpc/build_errors_schema.sh'
+  #         exit 1
+  #     fi >&2
+  #   timeout: 30
+  #   agents:
+  #     - "distro=amazonlinux"
+  #   branches: "!master"
 
   - label: "pytests"
     command: |
       source ~/.cargo/env && set -eux
+      cargo build -p neard --bin neard --features nightly
       cd pytest/buildkite_tests
       pip3 install --user -r ../requirements.txt
       pytest
